apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cert-parser-pdb
  namespace: cert-parser
  labels:
    app: cert-parser
spec:
  # Single replica: allow eviction (minAvailable: 0) so nodes can drain.
  # Set to 1 if you run multiple replicas and need continuous availability.
  minAvailable: 0
  selector:
    matchLabels:
      app: cert-parser
  unhealthyPodEvictionPolicy: AlwaysAllow

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cert-parser-network-policy
  namespace: cert-parser
  labels:
    app: cert-parser
spec:
  podSelector:
    matchLabels:
      app: cert-parser
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow ingress on port 8000 from all sources.
  # Kubelet health probes originate from the node's primary network interface, NOT
  # from a pod, so `podSelector: {}` cannot be used — it would silently block them.
  # The Service is ClusterIP-only, so port 8000 is unreachable from outside the cluster.
  - ports:
    - port: 8000
      protocol: TCP
  # Allow Prometheus to reach port 8000 from the monitoring namespace
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: monitoring
  egress:
  # DNS resolution
  - ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # HTTPS: OIDC token endpoint, SFC login, certificate download
  - ports:
    - protocol: TCP
      port: 443
  # HTTP: internal services (if any)
  - ports:
    - protocol: TCP
      port: 80
  # PostgreSQL
  - ports:
    - protocol: TCP
      port: 5432
